In [2]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr2 = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])
print(arr2)
print(type(arr2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [5]:
li1 = [
    [1, 2, 3], 
    [4, 5, 6],
    [1, 2, 3], 
    [4, 5, 6],
    [1, 2, 3], 
    [4, 5, 6],
    [1, 2, 3], 
    [4, 5, 6],
    [1, 2, 3], 
    [4, 5, 6],
    [1, 2, 3], 
    [4, 5, 6],
]
print(li1)
print(type(li1))

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]
<class 'list'>


In [6]:
arr3 = np.array([
    [[1, 2],
     [3, 4]], 
    [[5, 6],
     [7, 8]]
])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [8]:
ones = np.ones((2, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
range_arr = np.arange(1, 10, 2)
print(range_arr)

[1 3 5 7 9]


In [10]:
# 데이터 타입
정수 = np.array([1, 2, 3, 4, 5])
정수.dtype

dtype('int64')

In [11]:
실수 = np.array([1.5, 2.5, 3.5])
실수.dtype

dtype('float64')

In [12]:
# 배열 속성
arr1 = np.array([1, 2, 3, 4])
arr1.shape

(4,)

In [13]:
arr2 = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])
arr2.shape

(2, 3)

In [14]:
arr3 = np.array([
    [[1, 2],
     [3, 4]], 
    [[5, 6],
     [7, 8]]
])
arr3.shape

(2, 2, 2)

In [16]:
# ndim 
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [17]:
# size - 배열의 총 요소 수를 알려준다
arr1 = np.array([1, 2, 3, 4])
print(arr1.size)

4


In [18]:
arr2 = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])
print(arr2.size)

6


In [19]:
arr3 = np.array([
    [[1, 2],
     [3, 4]], 
    [[5, 6],
     [7, 8]]
])
print(arr3.size)

8
